volumes:
  postgres-data:
    external: true   
  pgadmin:
    external: true
services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
        - postgres-data:/var/lib/postgresql/data
        - ./workouts/data:/data
    environment:
        - POSTGRES_MULTIPLE_DATABASES=accounts,financials,goals
        - POSTGRES_PASSWORD=test-databases
    ports:
        - "15432:5432"
  financials:
    build:
      context: ./financials
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./financials:/app
    depends_on:
      - postgres 
    environment:
      DATABASE_URL: postgresql://financials:password@postgres:5432/financials
      WAIT_HOSTS: postgres:5432
      PGHOST: postgres
      PGDATABASE: financials
      PGUSER: postgres
      PGPASSWORD: test-databases
      # SIGNING_KEY: <<SECRET VALUE>>
  goals:
    build:
      context: ./goals
      dockerfile: ./Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ./goals:/app
    depends_on:
      - postgres 
    environment:
      DATABASE_URL: postgresql://goals:password@postgres:5432/goals
      WAIT_HOSTS: postgres:5432
      PGHOST: postgres
      PGDATABASE: goals
      PGUSER: postgres
      PGPASSWORD: test-databases
      # SIGNING_KEY: <<SECRET VALUE>>
  accounts:
    build:
      context: ./accounts
      dockerfile: ./Dockerfile.dev
    ports:
      - "8002:8002"
    volumes:
      - ./accounts:/app
    depends_on:
      - postgres 
    environment:
      DATABASE_URL: postgresql://accounts:password@postgres:5432/accounts
      WAIT_HOSTS: postgres:5432
      # DJWTO_SIGNING_KEY: 30bd16c09e22f5e7e51ba5885e8fd943d27377f3e249fdf36cbf367cece6613f
  # ghi:
  #   image: node:lts-bullseye
  #   command: /bin/bash run.sh
  #   working_dir: /app
  #   volumes:
  #       - ./ghi:/app
  #   ports:
  #       - "3000:3000"
  #   environment:
  #       HOST_OS: ${OS}
  #       NODE_ENV: development
  #       HOST: "0.0.0.0"
  #       REACT_APP_USERS: http://localhost:8001
  #       REACT_APP_WORKOUTS: http://localhost:8000
  pgadmin:
    image: dpage/pgadmin4
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
        - "8060:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: 'shelenells@gmail.com'
        PGADMIN_DEFAULT_PASSWORD: 'password'